{
 "title": "NetApp Detail: Volume - Details",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(volume_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(volume_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\",cluster=\"$Cluster\"}, svm)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(volume_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}, volume)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume Average Latency",
   "type": "stat",
   "description": "Average Latency of top $TopResources volumes",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(topk($TopResources, volume_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}))/1000"
    }
   ]
  },
  {
   "title": "Volume Total Throughput",
   "type": "stat",
   "description": "Throughput of top $TopResources volumes",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(topk($TopResources, volume_write_data+volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}))"
    }
   ]
  },
  {
   "title": "Volume Total IOPs",
   "type": "stat",
   "description": "IOPs of top $TopResources volumes",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(topk($TopResources, volume_total_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}))"
    }
   ]
  },
  {
   "title": "Volume Top Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, volume_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Top Average Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, volume_write_data+volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Top IOPs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, volume_total_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Table Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumes in Cluster",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_new_status{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_size_total{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_size_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_sis_dedup_saved{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_sis_compress_saved{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_sis_dedup_saved+volume_sis_compress_saved{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_space_logical_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_space_physical_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      }
     ]
    },
    {
     "title": "Top Volume Read Latency",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top Volume Read Throughput",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top Volume Read IOPS",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top Volume Write Latency",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top Volume Write Throughput",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top Volume Write IOPS",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume WAFL Layer Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Read Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Read IOPs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Write IOPs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Volume End-to-End QoS Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "QoS Volume Read Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "QoS Volume Read Throughput",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "QoS Volume Read IOPS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "QoS Volume Write Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "QoS Volume Write Throughput",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "QoS Volume Write IOPS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "QoS Volume Sequential Reads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_sequential_reads{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "QoS Volume Sequential Writes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_sequential_writes{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Volume QoS Resource Latency Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Latency from Network",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"network\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volume Latency from Throttle",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"throttle\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volume Latency from Frontend",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"frontend\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volume Latency from Cluster",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"cluster\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volume Latency from Backend",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"backend\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volume Latency from Disk",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"disk\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volume Latency from Suspend",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"suspend\"})/1000",
       "legendFormat": "{{svm}} / {{volume}} "
      }
     ]
    },
    {
     "title": "Volume Latency from Cloud",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"cloud\"})/1000",
       "legendFormat": "{{svm}} / {{volume}} "
      }
     ]
    },
    {
     "title": "Volume Latency from NVLog Mirroring",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"nvlog\"})/1000",
       "legendFormat": "{{svm}} / {{volume}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Top Volume Fabricpool Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  { "title": "Per Volume Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Per Volume Space Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes", "label": "Used" }
   ],
   "targets": [
    {
     "expr": "volume_size{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}} - Volume Total Size"
    },
    {
     "expr": "volume_space_physical_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}} - Physical Space Used"
    },
    {
     "expr": "volume_space_logical_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}} - Logical Space Used"
    },
    {
     "expr": "volume_size_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}} - Volume Size Used"
    }
   ]
  },
  {
   "title": "Per Volume Space Used Percent",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percent", "label": "%" }
   ],
   "targets": [
    {
     "expr": "volume_space_physical_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}} - Physical Space Used"
    },
    {
     "expr": "volume_space_logical_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}} - Logical Space Used"
    },
    {
     "expr": "volume_size_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}} - Volume Size Used"
    }
   ]
  },
  {
   "title": "Per Volume Snapshot Space Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes", "label": "IOPs/TB" }
   ],
   "targets": [
    {
     "expr": "volume_snapshots_size_available{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}} - Snapshot Size Available"
    },
    {
     "expr": "volume_snapshot_reserve_size{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}} - Snapshot Reserve Size"
    },
    {
     "expr": "volume_snapshot_reserve_available{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}} - Snapshot Reserve Available"
    },
    {
     "expr": "volume_snapshots_size_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}} - Snapshot Size Used"
    }
   ]
  },
  {
   "title": "Per Volume Snapshot Space Used Percent",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percent", "label": "%" }
   ],
   "targets": [
    {
     "expr": "volume_snapshot_reserve_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}} - Snapshot Reserve"
    },
    {
     "expr": "volume_snapshot_reserve_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}} - Snapshot Reserve Used"
    },
    {
     "expr": "volume_size_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}} - Volume Size Used"
    }
   ]
  }
 ]
}